version: "3"

services:
    flask_depot_dev:
        image: flask_depot_dev:1.00
        container_name: flask_depot_dev
        restart: unless-stopped
        command: manage.py runserver --host=0.0.0.0 --port=5002
        build:
            context: ../
            dockerfile: .dev-tools/Dockerfile
        ports:
            - "5002:5002"
        volumes:
            - ..:/usr/app