version: "3"

services:
    flask_vrp_origin_dev:
        image: flask_vrp_origin_dev:1.00
        container_name: flask_vrp_origin_dev
        restart: unless-stopped
        command: manage.py runserver --host=0.0.0.0 --port=5003
        build:
            context: ../
            dockerfile: .dev-tools/Dockerfile
        ports:
            - "5003:5003"
        volumes:
            - ..:/usr/app